# Generated by Django 3.2.20 on 2025-01-13 16:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_editpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='editpage',
            name='heading',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='editpage',
            name='section_name',
            field=models.CharField(choices=[('about_us', 'Home | About Us'), ('mission', 'Home | Our Mission'), ('vision', 'Home | Our Vision'), ('Volunteer', 'Home | Volunteer'), ('footer', 'Home | Footer')], max_length=100, unique=True),
        ),
    ]
