# Generated by Django 3.2.20 on 2025-01-13 16:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250113_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpage',
            name='heading',
            field=ckeditor.fields.RichTextField(blank=True, max_length=35),
        ),
    ]
