# Generated by Django 3.2.20 on 2025-01-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_editpage_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editpage',
            name='section_name',
            field=models.CharField(choices=[('h1', 'Home | Heading 1'), ('h2', 'Home | Heading 2'), ('h3', 'Home | Heading 3'), ('about_us', 'Home | About Us'), ('mission', 'Home | Our Mission'), ('vision', 'Home | Our Vision'), ('Volunteer', 'Home | Volunteer'), ('footer', 'Home | Footer'), ('aboutUs', 'About Us | About Us'), ('our_Programs', 'Our Programs | Goddess Care Initiative'), ('reach', 'Our Programs | Our Reach '), ('team1', 'Our Team | Kelly'), ('team2', 'Our Team | Elsie'), ('team3', 'Our Team | Loise')], max_length=100, unique=True),
        ),
    ]
