# Generated by Django 3.2.20 on 2024-10-28 16:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('about_us', 'About Us'), ('mission', 'Our Mission'), ('vision', 'Vision')], max_length=100, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
    ]
